openapi: 3.0.0

info:

  title: 'APIs.io Linter API'
  description: 'This is the API definition for the APIs.io linter API, allowing for linting APIs.json and OpenAPI.'
  version: V1

  contact:
    name: Kin Lane
    email: info@apievangelist.com

servers:
  - url: https://dqkupdnj9l.execute-api.us-east-1.amazonaws.com/staging    

tags:

  - name: Linter
    description: The linter for APIs.io.     
    
paths:

  /linter/apisjson:
        
    post:
      summary: Submit API
      description: 'Submit an API to be included in the index.'
      operationId: addAPI
      tags:
        - Linter
      requestBody:
        $ref: "#/components/requestBodies/APIsJSON"
      responses:
        "201":
          description: 201 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Linting"
      security:
        - api_key: []                
                
  /linter/openapi:

    post:
      summary: Submit API
      description: 'Submit an API to be included in the index.'
      operationId: addAPI
      tags:
        - Linter
      requestBody:
        $ref: "#/components/requestBodies/OpenAPI"
      responses:
        "201":
          description: 201 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Linting"
      security:
        - api_key: []  
                     

components:

  requestBodies:

    APIsJSON:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/APIsJSON"
      required: true

    OpenAPI:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/OpenAPI"
      required: true
                      
  
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
  
  schemas:

    OpenAPI:
      type: object
      description: 'An JSON API object with metadata, data, and links.'
      
      properties:
        meta:
          type: string

      required:
      - meta
    

    APIsJSON:
      type: object
      required:
      - name
      
      properties:
      
        name:
          type: string
          description: The name of the service described
          minLength: 5

    Linting:
      type: object
      description: 'An JSON API object with metadata, data, and links.'
      
      properties:
        meta:
          type: string

      required:
      - meta